SELECT 
    pp.id,
    pp.name,
    EXTRACT(YEAR FROM AGE(pp.FINISH_DATE, pp.START_DATE)) * 12 + EXTRACT(MONTH FROM AGE(pp.FINISH_DATE, pp.START_DATE)) as MONTH_COUNT,
    pp.START_DATE ,
    pp.FINISH_DATE
FROM project pp
WHERE EXTRACT(YEAR FROM AGE(pp.FINISH_DATE, pp.START_DATE)) * 12 + EXTRACT(MONTH FROM AGE(pp.FINISH_DATE, pp.START_DATE)) =
    (SELECT max(EXTRACT(YEAR FROM AGE(p.FINISH_DATE, p.START_DATE)) * 12 + EXTRACT(MONTH FROM AGE(p.FINISH_DATE, p.START_DATE)))
        FROM project p
    );